Repository sarthology/ovuli, pull requests merged in 2020-03, with the labels that each got.

#20 chore: prevent mixing up of lock files
  .gitignore
  .npmrc
Labels: gssoc20

#19 Added Docusaurus for Documentation
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  docs/doc1.md
  docs/doc2.md
  docs/doc3.md
  docs/exampledoc4.md
  docs/exampledoc5.md
  website/README.md
  website/blog/2016-03-11-blog-post.md
  website/blog/2017-04-10-blog-post-two.md
  website/blog/2017-09-25-testing-rss.md
  website/blog/2017-09-26-adding-rss.md
  website/blog/2017-10-24-new-version-1.0.0.md
  website/core/Footer.js
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/css/custom.css
  website/static/img/favicon.ico
  website/static/img/oss_logo.png
  website/static/img/undraw_code_review.svg
  website/static/img/undraw_monitor.svg
  website/static/img/undraw_note_list.svg
  website/static/img/undraw_online.svg
  website/static/img/undraw_open_source.svg
  website/static/img/undraw_operating_system.svg
  website/static/img/undraw_react.svg
  website/static/img/undraw_tweetstorm.svg
  website/static/img/undraw_youtube_tutorial.svg
Labels: gssoc20

#28 [Docs]: update contributing guidelines
  CONTRIBUTING.md
Labels: documentation, gssoc20

#32 Added Installation Guide for expo, to run app on mobile
  README.md
  assests/images/Img.png
  assests/images/Img1.png
  assests/images/Img2.png
Labels: gssoc20

#33 Calendar Implemented in Last Period Screen
  .expo/settings.json
  package.json
  src/screens/ProfileScreen/LastPeriodScreen.js
  yarn.lock
Labels: gssoc20, medium

#34 Fixed a typo
  CONTRIBUTING.md
Labels: Easy, gssoc20

#36 Typo error
  CONTRIBUTING.md
Labels: gssoc20

#40 Update YourNameScreen.js
  .expo/packager-info.json
  .expo/settings.json
  src/screens/ProfileScreen/YourNameScreen.js
  yarn.lock
Labels: Easy, gssoc20

#45 dummy files and thier refrences removed fixes issue #31
  docs/doc1.md
  docs/doc2.md
  docs/doc3.md
  docs/exampledoc4.md
  docs/exampledoc5.md
  website/blog/2016-03-11-blog-post.md
  website/blog/2017-04-10-blog-post-two.md
  website/blog/2017-09-25-testing-rss.md
  website/blog/2017-09-26-adding-rss.md
  website/blog/2017-10-24-new-version-1.0.0.md
  website/core/Footer.js
  website/pages/en/help.js
  website/pages/en/index.js
  website/sidebars.json
  website/siteConfig.js
Labels: Easy, gssoc20

#46 Added splash screen
  .expo/packager-info.json
  .expo/settings.json
  app.json
Labels: beginner, gssoc20

#44 improves nameScreen
  App.js
  src/screens/ProfileScreen/AvgCycleScreen.js
  src/screens/ProfileScreen/LastPeriodScreen.js
  src/screens/ProfileScreen/YourNameScreen.js
  yarn.lock
Labels: gssoc20, medium

#51 Splash Screen
  .expo/settings.json
  app.json
  wireframes/GetStarted.png
Labels: beginner, gssoc20

#59 Integrated ESLint with prettier
  .eslintrc.json
  package.json
  yarn.lock
Labels: gssoc20, medium

#63 Configuring github actions
  .github/workflows/greeting.yml
Labels: Easy, gssoc20

#70 Calculations using ovuli library
  .expo/settings.json
  src/screens/HomeScreen/index.js
  src/screens/ProfileScreen/LastPeriodScreen.js
  yarn.lock
Labels: gssoc20, hard

#66 Cycle calculator
  .expo/packager-info.json
  App.js
  src/screens/ProfileScreen/CalculatingCyclePeriodPage.js
Labels: gssoc20, medium

#76 Created pull request template
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: beginner, gssoc20

#79 Fix: Name Screen Design
  .eslintrc.json
  .expo/packager-info.json
  .expo/settings.json
  App.js
  app.json
  src/screens/ProfileScreen/AvgCycleScreen.js
  src/screens/ProfileScreen/YourNameScreen.js
  wireframes/assets/Your_Name/How_can_we_call_you.png
  wireframes/assets/Your_Name/bottom.png
  wireframes/assets/Your_Name/top.png
Labels: beginner, gssoc20

#80 feat: New Design Screen Added
  .expo/settings.json.2779781679
  App.js
  android/.project
  android/.settings/org.eclipse.buildship.core.prefs
  android/app/src/main/java/com/ovuli/MainActivity.java
  android/app/src/main/java/com/ovuli/generated/BasePackageList.java
  src/screens/ProfileScreen/LanguageScreen.js
  src/screens/ProfileScreen/YourNameScreen.js
  wireframes/assets/Lang_Screen/bottom.png
  wireframes/assets/Lang_Screen/please_select_your_language.png
  wireframes/assets/Lang_Screen/top.png
  wireframes/assets/Lang_Screen_SVG/bottom.svg
  wireframes/assets/Lang_Screen_SVG/top.svg
  wireframes/onboard-wirefames/onboard-page1.png
  wireframes/onboard-wirefames/onboard-page2.png
Labels: gssoc20, medium

#81 testing for ovuli.js
  .expo/packager-info.json
  src/util/ovuli.test.js
Labels: gssoc20, hard

#90 Padding to next button in Every Page
  .expo/packager-info.json
  .expo/settings.json
  src/screens/ProfileScreen/AvgCycleScreen.js
  src/screens/ProfileScreen/LanguageScreen.js
  src/screens/ProfileScreen/LastPeriodScreen.js
  src/screens/ProfileScreen/YourNameScreen.js
Labels: Easy, gssoc20

#104 Language files added
  languageBase/A_LANG_CODE.json
  languageBase/as.json
  languageBase/be.json
  languageBase/bo.json
  languageBase/do.json
  languageBase/en.json
  languageBase/gu.json
  languageBase/hi.json
  languageBase/kn.json
  languageBase/ko.json
  languageBase/ks.json
  languageBase/ma.json
  languageBase/ml.json
  languageBase/mn.json
  languageBase/mr.json
  languageBase/ne.json
  languageBase/or.json
  languageBase/pa.json
  languageBase/sa.json
  languageBase/sample.json
  languageBase/sd.json
  languageBase/sn.json
  languageBase/ta.json
  languageBase/te.json
  languageBase/ur.json
  src/screens/ProfileScreen/LanguageScreen.js
Labels: gssoc20, medium

#103 Add page to capture past period dates #94 resolved
  .expo/settings.json
  src/screens/ProfileScreen/SecondLastPeriodScreen.js
  src/screens/ProfileScreen/ThirdLastPeriodScreen.js
Labels: beginner, gssoc20

#128 Input Screen and Keyboard
  .expo/packager-info.json
  .expo/settings.json
  package.json
  src/screens/ProfileScreen/YourNameScreen.js
  yarn.lock
Labels: gssoc20, medium

#129 Changed the icon color
  App.js
Labels: Easy, gssoc20

#131 Calculations using calculateAverageCycle
  App.js
  src/screens/HomeScreen/index.js
  src/screens/ProfileScreen/LastPeriodScreen.js
  src/screens/ProfileScreen/SecondLastPeriodScreen.js
Labels: gssoc20, hard

#130 Continue button removed
  .expo/packager-info.json
  App.js
  src/screens/ProfileScreen/DoYouKnow.js
Labels: beginner, gssoc20

#127 Added typescript of each language
  App.js
  languageBase/A_LANG_CODE.json
  languageBase/as.json
  languageBase/be.json
  languageBase/bo.json
  languageBase/do.json
  languageBase/en.json
  languageBase/gu.json
  languageBase/hi.json
  languageBase/kn.json
  languageBase/ko.json
  languageBase/ks.json
  languageBase/ma.json
  languageBase/ml.json
  languageBase/mn.json
  languageBase/mr.json
  languageBase/ne.json
  languageBase/or.json
  languageBase/pa.json
  languageBase/sa.json
  languageBase/sd.json
  languageBase/sn.json
  languageBase/ta.json
  languageBase/te.json
  languageBase/ur.json
  src/screens/ProfileScreen/LanguageScreen.js
Labels: gssoc20, hard
